version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb/los:/data/configdb
    ports:
      - 27017:27017
    env_file:
      - config/config.env
