// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: status.proto

package grpcProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatusGrpcClient is the client API for StatusGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusGrpcClient interface {
	Status(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type statusGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusGrpcClient(cc grpc.ClientConnInterface) StatusGrpcClient {
	return &statusGrpcClient{cc}
}

func (c *statusGrpcClient) Status(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/grpcProto.StatusGrpc/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusGrpcServer is the server API for StatusGrpc service.
// All implementations must embed UnimplementedStatusGrpcServer
// for forward compatibility
type StatusGrpcServer interface {
	Status(context.Context, *RequestStatus) (*ResponseStatus, error)
	mustEmbedUnimplementedStatusGrpcServer()
}

// UnimplementedStatusGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedStatusGrpcServer struct {
}

func (UnimplementedStatusGrpcServer) Status(context.Context, *RequestStatus) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedStatusGrpcServer) mustEmbedUnimplementedStatusGrpcServer() {}

// UnsafeStatusGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusGrpcServer will
// result in compilation errors.
type UnsafeStatusGrpcServer interface {
	mustEmbedUnimplementedStatusGrpcServer()
}

func RegisterStatusGrpcServer(s grpc.ServiceRegistrar, srv StatusGrpcServer) {
	s.RegisterService(&StatusGrpc_ServiceDesc, srv)
}

func _StatusGrpc_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusGrpcServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcProto.StatusGrpc/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusGrpcServer).Status(ctx, req.(*RequestStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusGrpc_ServiceDesc is the grpc.ServiceDesc for StatusGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcProto.StatusGrpc",
	HandlerType: (*StatusGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _StatusGrpc_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status.proto",
}
